FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache libpq

COPY requirements.txt .
RUN apk add --no-cache --virtual .build-deps gcc musl-dev libpq-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del .build-deps

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
